services:
  bs_web:
    build:
      context: ./bs_web
    container_name: bs_web
    ports:
      - "30001:30001"
    environment:
      - HOST_IP=192.168.30.10
    networks:
      - bs_network

  bs_batch:
    build:
      context: ./bs_batch
    container_name: bs_batch
    ports:
      - "30002:30002"
    environment:
      - HOST_IP=192.168.30.10
    networks:
      - bs_network

networks:
  bs_network: